name: Build and Upload Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Build with Maven
        uses: KillionRevival/maven-builder-action@v2
        id: build-step
        with:
          java-version: 8
          token: ${{ secrets.PAT }}

      - name: Upload Release Asset
        uses: KillionRevival/release-action@v2
        with:
          jar-path: ${{ steps.build-step.outputs.jar-path }}
